# Generated by Django 4.2.7 on 2023-11-26 04:32

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
