# Generated by Django 4.2.7 on 2023-11-27 01:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
