# Generated by Django 5.0 on 2023-12-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_user_verificationcode_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='author',
        ),
    ]
